### PR TITLE
Fix compilation error in Swift 3.2

### PR DESCRIPTION
**Pull request by AliSoftware**
It seems that in Swift 3.2, calling `self.init(value)` from within the `String.init(ArgumentParser)` doesn't compile:

> 🛑 A non-failable initializer cannot delegate to failable initializer 'init' written with 'init?'

(But it does compile in Swift 4.0)

Given `value` is already a `String` extracted by `parser.shift()`, there's actually no need to call the init, as we can use `self = value` directly, which both compiles in Swift 3.2 and in Swift 4.0

### CODE REVIEW

**Comment by kylef** [comment]
Commander 0.7.0 did drop Swift < 4.0 support. However if this is all it takes then we can add it back. Would you be able to configure Travis CI to be able to test Swift 3.2?

There doesn't seem to be any stand alone 3.2 release and appears you have to use the Swift 4 compiler. If that is the case, what is the point in Swift 3.2 support since the user already has Swift 4 compiler?

**Comment by AliSoftware** [comment]
I could try to add the Travis config later.

The point of supporting 3.2 even when you use the Swift 4 compiler is:

* I tested if it compiled with 3.2 but maybe it's also all it takes to compile with Swift 3.0 too? Worth checking
* When integrating Commander via CocoaPods, at least with the current CP version, the `SWIFT_VERSION` of all pods inherit the `SWIFT_VERSION` of the parent project, so if the parent project is in Swift 3.2 has it hasn't migrated yet, Commander will default to be built with Swift 3.2 too. We can still add a `post_install` hook to change the `SWIFT_VERSION=4.0` for Commander, but if that change is all it takes to make it compile in 3.2, it could be nice for ease of integration for people less used to install hooks etc

**Comment by kylef** [comment]
Given it's a few years later, @AliSoftware do you still care about Swift 3 support? I can get this into a patch release if you do.

**Comment by AliSoftware** [comment]
Nope no need to support anymore 😉
